# JWT profile-specific overrides

# custom property
students.email.domain=jwt-flyway-domain.com

# Flyway remains enabled in this profile too
spring.flyway.enabled=true

# Security mode override for JWT profile
app.security.authentication=JWT
