# JWT profile-specific overrides

# custom property
students.email.domain=jwt-flyway-domain.com

# Flyway remains enabled in this profile too
spring.flyway.enabled=true

# Security mode override for JWT profile
app.security.authentication=jwt

# Disable auto-running batch jobs on application startup
spring.batch.job.enabled=false

# Spring Boot manages Batch Metadata tables automatically in H2
spring.batch.jdbc.initialize-schema=always

# Allow Spring Boot to override bean definitions in this profile (e.g., jobLauncher)
spring.main.allow-bean-definition-overriding=true
