CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

ALTER TABLE users ADD COLUMN role_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id);

INSERT INTO permissions (code, description)
VALUES
    ('CAN_READ', 'Can read employee and task data'),
    ('CAN_WRITE', 'Can create employee data'),
    ('CAN_EDIT', 'Can edit employee data'),
    ('CAN_DELETE', 'Can delete employee data'),
    ('CAN_AUDIT', 'Can access audit endpoints');

INSERT INTO roles (code, description)
VALUES
    ('GUEST', 'Guest role with no privileged permissions'),
    ('USER', 'Standard authenticated user role'),
    ('ADMIN', 'Administrative role'),
    ('AUDITOR', 'Audit-focused role'),
    ('SUPERUSER', 'Super user role used by sample seed data');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code = 'CAN_READ'
WHERE r.code IN ('USER', 'ADMIN', 'AUDITOR', 'SUPERUSER');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code = 'CAN_WRITE'
WHERE r.code IN ('ADMIN', 'SUPERUSER');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code = 'CAN_EDIT'
WHERE r.code IN ('ADMIN', 'SUPERUSER');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code = 'CAN_DELETE'
WHERE r.code IN ('ADMIN', 'SUPERUSER');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code = 'CAN_AUDIT'
WHERE r.code IN ('AUDITOR', 'SUPERUSER');

UPDATE users u
SET role_id = (
    SELECT r.id
    FROM roles r
    WHERE r.code = REPLACE(COALESCE(u.role, 'ROLE_USER'), 'ROLE_', '')
);

UPDATE users
SET role_id = (SELECT id FROM roles WHERE code = 'USER')
WHERE role_id IS NULL;

ALTER TABLE users ALTER COLUMN role_id SET NOT NULL;

CREATE INDEX idx_users_role_id ON users (role_id);
